### ISSUE TITLE
Possibility to set 'HttpOnly' flag on cookies

### ISSUE THREAD

**Issue by eripa** [xyproto/cookie#2]
Add the option to configure cookies to set the HttpOnly flag.

https://www.owasp.org/index.php/HttpOnly

**Reason**: It would be good if [xyproto/permissionbolt](https://github.com/xyproto/permissionbolt) could have this for userstate cookies.

**Comment by xyproto** [comment]
Will look into using the `SetSecureCookiePathWithFlags` function for [permissionbolt](https://github.com/xyproto/permissionbolt).
